// import { Inter } from "next/font/google";
// import "./globals.css";
// import Provider from "./Provider/Provider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//       <Provider>
//             {children}
//             </Provider>   
//               </body>
//     </html>
//   );
// }

import './globals.css'
import { Metadata } from 'next'
import { headers } from 'next/headers'

import { cookieToInitialState } from 'wagmi'

import AppKitProvider from './context'
import { defaultWagmiConfig } from '@web3modal/wagmi'
import { polygonAmoy, polygonMumbai } from 'viem/chains'

// export const metadata = {
//   title: 'Concertify',
//   description: 'Generated by create next app'
// }

const projectId = "9f524b160b89610f0f2e2758bccb1215";

// 2. Create wagmiConfig
const metadata = {
  name: "Concertify",
  description: "AppKit Example",
  url: "https://web3modal.com", // origin must match your domain & subdomain
  icons: ["https://avatars.githubusercontent.com/u/37784886"],
};

const chains = [polygonMumbai, polygonAmoy];
const config = defaultWagmiConfig({
  chains,
  projectId,
  metadata,
});

export default function RootLayout({
  children
}) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <body>
        <AppKitProvider initialState={initialState}>{children}</AppKitProvider>
      </body>
    </html>
  )
}
